title: viktor-bd
description: Personal portfolio and project showcase of Viktor
baseurl: ""
url: https://viktor-bd.github.io

theme: cvless

# site settings
taglong: Portfolio, experiments, and projects by Viktor
tagshort: Portfolio
cv: true

# author settings
author:
  name: Viktor B. D.
  email: viktordorph@hotmail.com
photo: assets/files/photo.png
address: Aalborg, Denmark
phone: +45 29 93 90 69

# profile links
profile:
  # facebook: ""
  # x: ""
  # mastodon: ""
  # bluesky: ""
  # instagram: ""
  linkedin: https://www.linkedin.com/in/viktor-dorph-62604a141/
  # xing: ""
  # stackoverflow: ""
  # medium: ""
  github: https://github.com/viktor-bd

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never

pagination:
  enabled: true
  per_page: 5
  permalink: '/posts/:num/'